### PR TITLE
Readme update: Add section on how to compile kernel with silead_ts

### PR DESCRIPTION
**Pull request by userx14**
Sorry for creating so many pull requests, but I hadn't figured out that the only way to create separate pull requests is to use two branches.

### CODE REVIEW

**Comment by onitake** [comment]
Thanks for the patch, but I don't think the README is a good place for this kind of tutorial.
Also, it's distribution-specific.

Can you put it into a separate file instead (something `kernel-recompile-debian.md`) and replace the steps with a reference to that file plus specific instructions for creating the kernel patch?

**Comment by BenjaminRenz** [comment]
Ok, I will see what I can do.

**Comment by BenjaminRenz** [comment]
I hope that the latest edit is to your liking.
If not, could you please clarify what you mean by:
> plus specific instructions for creating the kernel patch?

**Comment by onitake** [comment]
Sorry @userx14 that I left this hanging for so long. I'll merge it now.

As for the additional request, this was about preparing and submitting a patch to https://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86.git/tree/drivers/platform/x86/touchscreen_dmi.c , so users can get out-of-the-box support for tested devices. But don't worry about that for now.

**Pull request merged**
