### PR TITLE
Add Trekstor Primebook-c11b

### PR DESCRIPTION
**Pull request by abcsds**
Hi, I include the patch for the linux50 kernel.

### CODE REVIEW

**Comment by abcsds** [comment]
Sorry about the force pushing, but I saw there was not much activity here and took the opportunity. I updated the sensor resolution. I was able to measure it with a fine point active stylus, and turned out to be different as that of the c11 model.

**Comment by onitake** [comment]
Don't worry, you can do what you want on your own branch.
Did you submit the kernel patch to linux-input?

**Comment by abcsds** [comment]
No, I haven't. I'm unfamiliar with the process, so I'm only now reading about it.

**Comment by onitake** [comment]
It's not that hard, make sure the patch is formatted accordingly and send it to: http://vger.kernel.org/vger-lists.html#linux-input
See https://www.spinics.net/lists/linux-input/msg59634.html for an example.

**Comment by bernhardu** [comment]
I guess the trekstorc11b.patch should not be needed anymore, as kernel v5.4 got this [patch commited](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/platform/x86/touchscreen_dmi.c?id=37d960a4d753605ca248baea577eaaa96f5dccf0), which uses the same config as the Primebook-C11.

**Comment by onitake** [comment]
Thanks for the info.

@abcsds Can you confirm that the mentioned kernel works for you?

And if you drop the patch from the branch, I'll squash-merge it.

**Comment by abcsds** [comment]
I can confirm that the patch worked. Thank you!

**Comment by bernhardu** [comment]
Hello @onitake, hello @abcsds,
as the kernel part is already in place I fear we still do not have a "Primebook C11" entry,
as new kernel now search just for "gsl1680-trekstor-primebook-c11.fw".
Should the original author of the kernel patch be contacted, if he might add the firmware
to onitake/gsl-firmware, or would it be sufficient to have the available c11b stored as c11 ?

**Comment by onitake** [comment]
I'm slightly confused: The patch you linked references a config for the C11.
As this config was already there in the kernel, I assumed that there is also a firmware for the C11.
If this is not the case, then that config should not exist and the patch shouldn't have been accepted in the first place.

@jwrdegoede Can you provide the firmware for the C11 and the C11B that is referenced in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/platform/x86/touchscreen_dmi.c#n624 ?
It should be named gsl1680-trekstor-primebook-c11.fw .

@abcsds How did you get the touchscreen working without the firmware?

**Comment by bernhardu** [comment]
@onitake: I guess the c11b firmware used by abcsds is part of this pull request,
and his patch really searched for a file named c11b (and uses slightly different resolution values).

**Comment by onitake** [comment]
@bernhardu That could be, but it doesn't explain where the firmware for the C11 is...

**Comment by onitake** [comment]
Fixed by @jwrdegoede in 4de14b2dd3c12bdc45edc23b9c7fa0220c828ead - thanks!

**Pull request closed without merging**
