### PR TITLE
Added firmware for Onda oBook 20 Plus

### PR DESCRIPTION
**Pull request by nerijus**
I didn't add gslx680-acpi firmware as I could not test it. mssl1680.fw is silead.ko firmware, please add it, as there are projects which use your firmwares (Bliss-x86).

### CODE REVIEW

**Comment by onitake** [comment]
Thanks, that's perfectly ok.

Is this device already in https://git.kernel.org/pub/scm/linux/kernel/git/dtor/input.git/tree/drivers/platform/x86/silead_dmi.c or are you going to submit a patch soon?
If yes, please tell me the file name so I can add it to https://github.com/onitake/gsl-firmware/tree/master/firmware/linux - or better yet, please push a commit that adds the file there.

**Comment by nerijus** [comment]
I didn't know about https://git.kernel.org/pub/scm/linux/kernel/git/dtor/input.git/tree/drivers/platform/x86/silead_dmi.c. I can make a patch, but I don't know where can I find DMI_MATCH(DMI_SYS_VENDOR), DMI_MATCH(DMI_PRODUCT_NAME)?

**Comment by nerijus** [comment]
And how do I know touchscreen size? By running evtest?

**Comment by onitake** [comment]
`dmidecode` should give you these values.

And as for the panel size, it's mostly a matter of try and error. But evtest should give you good clues, yes.
Perhaps there is a way to get them from the firmware, but nobody has found out how so far...

**Comment by onitake** [comment]
The name should reflect the Silead chip used, the manufacturer and the device name.
Remember that each firmware is unique for each device and should also have a unique name.

Unfortunately, there is no easy way to identify the chip other than opening the device and looking at its package... But if you can't or don't want to do that (and no pictures of the circuit board are available), just use `gsl1680-`. It's not really important.

**Comment by nerijus** [comment]
I found a picture and identified the chip - it's GSL3676. I made a patch to drivers/platform/x86/silead_dmi.c:
```
diff --git a/drivers/platform/x86/silead_dmi.c b/drivers/platform/x86/silead_dmi.c
index 266535c2a72f..1b6e9dfb6b15 100644
--- a/drivers/platform/x86/silead_dmi.c
+++ b/drivers/platform/x86/silead_dmi.c
@@ -171,6 +171,21 @@ static const struct silead_ts_dmi_data digma_citi_e200_data = {
        .properties     = digma_citi_e200_props,
 };
 
+static const struct property_entry onda_obook_20_plus_props[] = {
+       PROPERTY_ENTRY_U32("touchscreen-size-x", 1728),
+       PROPERTY_ENTRY_U32("touchscreen-size-y", 1148),
+       PROPERTY_ENTRY_BOOL("touchscreen-swapped-x-y"),
+       PROPERTY_ENTRY_STRING("firmware-name", "gsl3676-onda-obook-20-plus.fw"),
+       PROPERTY_ENTRY_U32("silead,max-fingers", 10),
+       PROPERTY_ENTRY_BOOL("silead,home-button"),
+       { }
+};
+
+static const struct silead_ts_dmi_data onda_obook_20_plus_data = {
+       .acpi_name      = "MSSL1680:00",
+       .properties     = onda_obook_20_plus_props,
+};
+
 static const struct dmi_system_id silead_ts_dmi_table[] = {
        {
                /* CUBE iwork8 Air */
@@ -271,6 +286,14 @@ static const struct dmi_system_id silead_ts_dmi_table[] = {
                        DMI_MATCH(DMI_BOARD_NAME, "Cherry Trail CR"),
                },
        },
+       {
+               /* Onda oBook 20 Plus */
+               .driver_data = (void *)&onda_obook_20_plus_data,
+               .matches = {
+                       DMI_MATCH(DMI_SYS_VENDOR, "INSYDE Corp."),
+                       DMI_MATCH(DMI_PRODUCT_NAME, "OBOOK 20 PLUS"),
+               },
+       },
        { },
 };

```
I recompiled the kernel, but it still tries to load silead/mssl1680.fw, not gsl3676-onda-obook-20-plus.fw, why?
```
[    8.379390] silead_ts i2c-MSSL1680:00: Silead chip ID: 0x80360000
[    8.539224] silead_ts i2c-MSSL1680:00: Direct firmware load for silead/mssl1680.fw failed with error -2
[    8.539240] silead_ts i2c-MSSL1680:00: Firmware request error -2
```

**Comment by nerijus** [comment]
dmidecode:
Vendor: INSYDE Corp.
Product Name: OBOOK 20 PLUS

**Comment by onitake** [comment]
@jwrdegoede can you help with this one?

**Comment by nerijus** [comment]
Actually dmidecode has 2 Product Name:
# dmidecode |grep -i product
	Product Name: OBOOK 20 PLUS
	Product Name: T210REV05
I tried with DMI_MATCH(DMI_PRODUCT_NAME, "T210REV05") instead of DMI_MATCH(DMI_PRODUCT_NAME, "OBOOK 20 PLUS"), didn't help.
Full dmidecode output attached.
I will try to debug it.
[dmidecode.txt](https://github.com/onitake/gsl-firmware/files/1545687/dmidecode.txt)

**Comment by nerijus** [comment]
It worked when I changed DMI_SYS_VENDOR, "INSYDE Corp." to DMI_SYS_VENDOR, "ONDA" (it seems DMI_SYS_VENDOR is the field Manufacturer). The patch is attached, and I sent it to maintainers.
[0001-Add-touchscreen-platform-data-for-the-Onda-oBook-20.patch.txt](https://github.com/onitake/gsl-firmware/files/1546128/0001-Add-touchscreen-platform-data-for-the-Onda-oBook-20.patch.txt)
Where do I send the gsl3676-onda-obook-20-plus.fw file?

**Comment by onitake** [comment]
Awesome, thank you very much!
Considering bf3f37d, I take it that you figured it out.
I will merge this right away.

**Comment by nerijus** [comment]
Thank you.
What about all the firmware files gsl*.fw? Will they be added to linux-firmware package?

**Comment by nerijus** [comment]
I see you added as "Tested: no" in readme. I have tested it, it works except the problem described in https://github.com/sigboe/gslX68X/issues/8

**Comment by onitake** [comment]
I don't think anybody is currently taking care of that... As the legal status of these firmwares is completely unknown, it will probably be difficult to offer them as a distribution package. But I'm not an expert on these matters. I should discuss this with jwrdegoede, he may know more.

About the tested flag: Sorry, that wasn't intended. I corrected it.

**Comment by nerijus** [comment]
I see. While the legal status is unknown I would suggest to make a release (called "silead-firmware" for example), what do you think? It should contain /lib/fimware/silead.*. It could be (more) convenient for some projects to include silead-firmware package instead of github pulls.

**Comment by enersia** [comment]
obook20 plus has two type of touch pannel.
v1, early v3 has sametype, later v3,v5 has same.
please describe your machine version on information.
obook20

**Comment by nerijus** [comment]
Mine is V5. If the code does not work for someone, he/she will have to update the code with their info. I cannot do it, as I do not own other types. But Windows driver is the same AFAIK, so it should probably work?

**Comment by ponces** [comment]
@nerijus and @onitake could you please help me on this one?
No matter what I do I can't make it to load the silead module for my firmware.
I already tried with the following configurations and I can't make it to work:

DMI_VENDOR_NAME, "TECLAST"
DMI_PRODUCT_NAME, "X3 Plus"

DMI_VENDOR_NAME, "TECLAST"
DMI_PRODUCT_NAME, "tPAD"

DMI_BOARD_VENDOR, "TECLAST"
DMI_BOARD_NAME, "tPAD"

What should I do?
This is the output of dmidecode - [dmidecode_teclast.txt](https://github.com/onitake/gsl-firmware/files/1583146/dmidecode_teclast.txt)

**Comment by nerijus** [comment]
DMI_SYS_VENDOR, "TECLAST" 
DMI_PRODUCT_NAME, "X3 Plus"
should work.

**Comment by ponces** [comment]
It keeps showing me this error:

```
# dmesg | grep silead
[    3.270331] silead_ts i2c-MSSL1680:00: Silead chip ID: 0x80360000
[    3.415390] silead_ts i2c-MSSL1680:00: Direct firmware load for silead/mssl1680.fw failed with error -2
[    3.415395] silead_ts i2c-MSSL1680:00: Firmware request error -2
[    3.415479] silead_ts: probe of i2c-MSSL1680:00 failed with error -2
```

**Comment by nerijus** [comment]
With DMI_SYS_VENDOR, "TECLAST"
DMI_PRODUCT_NAME, "X3 Plus"
?

**Comment by ponces** [comment]
Yes!

**Comment by nerijus** [comment]
Could you please show you code (or diff)?

**Comment by ponces** [comment]
This is the patch that I was preparing - [0001-platform-x86-silead_dmi-Add-entry-for-the-Teclast-X3.patch.txt](https://github.com/onitake/gsl-firmware/files/1583245/0001-platform-x86-silead_dmi-Add-entry-for-the-Teclast-X3.patch.txt)
Thank you for your help.

**Comment by nerijus** [comment]
I don't know then.

**Comment by onitake** [comment]
Did you double-check if the names have any trailing spaces in them?

**Comment by ponces** [comment]
Yes! It's okay, I'll try again later when I have more information on this topic...

**Comment by ponces** [comment]
It's working!
I could only make it to work using a combination of these three lines:
DMI_MATCH(DMI_SYS_VENDOR, "TECLAST"),
DMI_MATCH(DMI_PRODUCT_NAME, "X3 Plus"),
DMI_MATCH(DMI_BOARD_NAME, "X3 Plus")

Thank you for your help!

**Comment by onitake** [comment]
Awesome, thank you!
I merged your PR already.

**Pull request merged**
