### PR TITLE
Add Dexp Ursus KX210i

### PR DESCRIPTION
**Pull request by Avdeev-AV**

### CODE REVIEW

**Comment by jwrdegoede** [comment]
@Avdeev-AV thank you for this firmware pull-request.

Can you perhaps also write a patch for the mainline kernel drivers/platform/x86/touchscreen_dmi.c file to make the kernel automatically use the right firmware file (and let the kernel know the config parameters like the x and y coordinate ranges) ?

**Comment by Avdeev-AV** [comment]
Hello! Yes, i'll do that

**Comment by jwrdegoede** [comment]
> Hello! Yes, i'll try do that. May I ask a question if i need help?

Yes certainly if you need any help / have any questions don't hesitate to ask.

**Comment by jwrdegoede** [comment]
Note there are some docs on this here: https://github.com/onitake/gsl-firmware/#silead_ts

**Comment by Avdeev-AV** [comment]
https://lore.kernel.org/linux-input/ZE4gRgzRQCjXFYD0@avdeevavpc/T/#u

**Comment by onitake** [comment]
@Avdeev-AV Thank you very much!

@jwrdegoede The PR looks good to me, I'll leave it up to you merge it.

**Comment by jwrdegoede** [comment]
@Avdeev-AV, thank you for the kernel patch. I have just merged the kernel patch, so let me now also merge this :)

**Pull request merged**
