### PR TITLE
Added firmware for Utok i800 remove wrong frimware from Chuwi vi8 folder

### PR DESCRIPTION
**Pull request by barni2000**
I discover some mistake, my firmware file was in the chuwi vi8 folder, but i havent got chuwi vi8.
I moved these files to Utok folder and I add the new style firmware.

### CODE REVIEW

**Comment by onitake** [comment]
Shame on you! :)

**Comment by onitake** [comment]
Umm... Can you please recheck your patch?
Your previous commit was into chuwi/hi8, this one moves the files in chuwi/vi8.

**Comment by barni2000** [comment]
I haven't got previous commit.

**Comment by onitake** [comment]
Sorry, I got it all mixed up. @djvdorp submitted a pull request for the hi8 Windows drivers.
I thought this one was moving those files, but accidentally went for the wrong folder.

I'm applying your patch.

**Pull request merged**
