### PR TITLE
fw_extractor: fix problem of '[ x]' in readelf -S output that leads to wrong offset

### PR DESCRIPTION
**Pull request by Icenowy**
At least this problem exists on my binutils 2.26.20160125

### CODE REVIEW

**Comment by onitake** [comment]
A better fix would be a proper regular expression to extract the correct field, and I also think this should be done in pure python instead of relying on shell tools. The whole Popen call could then be simplified, as the regex would only match the .rodata lines.

Something like:
`rodata = re.compile(r'\.rodata........([0-9a-f]{6})...')
for line in Popen(['readelf', '-S ', filename]):
    result = rodata.match(line)
    if result:
        print('Got address: 0x%06x' % (result.group(1)))`

**Comment by onitake** [comment]
Can you provide a kernel module where the current implementation fails?
I'm going to merge the bugfix, but I'd like to have some test cases.
Thanks.

**Comment by Icenowy** [comment]
@onitake https://mirror.anthonos.org/misc/gslX680-aoson-m751s.ko is such a ko (it's from an Allwinner A33 tablet with gsl1680

**Comment by onitake** [comment]
Thanks, I'll check it out.

**Pull request merged**
