### PR TITLE
Add techBite Arc 10.6

### PR DESCRIPTION
**Pull request by wiktorciurej**

### CODE REVIEW

**Comment by onitake** [comment]
Great, thanks!
Can you also post a link to the Linux kernel patch that adds this tablet?

**Comment by wiktorciurej** [comment]
Sure @onitake, as soon as I send it to review.

**Comment by wiktorciurej** [comment]
https://patchwork.kernel.org/patch/11466309/ @onitake

**Comment by onitake** [comment]
Thanks!

**Pull request merged**
