### PR TITLE
new firmware

### PR DESCRIPTION
**Pull request by tapeguy**
Thank you for this driver!

### CODE REVIEW

**Comment by onitake** [comment]
Thank you!

Two things:

Please keep a directory depth of two levels (manufacturer/device). Try to keep only the unique part of the device name. README.md specifies the name in full length, so people should find the firmware even if the folder name is shortened.

And please specify the touchscreen resolution in your README, not the display resolution.

**Comment by tapeguy** [comment]
Hi,
Regarding the touchscreen resolution - I figured this out via trial and error until the cursor scaled properly on my screen.  Is there a way to determine this more accurately?
thanks
Ben

**Comment by onitake** [comment]
Unfortunately not, at the moment. I believe there may be a way to extract it from the firmware, but I haven't found time to analyse this yet. If you obtain the firmware in GSL_TS_CFG.h format (or unscramble the SileadTouch.fw), there may be something in the data structure gsl_config_data_id at the top of the file.

If you'd like to, please investigate and share your findings. It would be very appreciated.

**Comment by onitake** [comment]
Here's a little dump tool for the gsl_config_data_id block: https://gist.github.com/onitake/5b5e4f1d46c28931b92c

**Comment by onitake** [comment]
I pulled your patch and added the changes myself.

Thanks!

**Pull request merged**
