### PR TITLE
Improve documentation on how to submit kernel patches

### PR DESCRIPTION
**Pull request by onitake**
Kernel support for more devices has picked up lately.

To make it a bit easier to understand the submission process, I added a few more references to the readme.

### CODE REVIEW

**Comment by onitake** [comment]
@jwrdegoede Could you take a look at the changes? Thanks!

**Comment by jwrdegoede** [comment]
@onitake, I have seen your request to take a look at this, but I have not been able to make the time to look at this so far, sorry.

I do still have it on my todo list somewhere...

If you think the PR is a nice improvement to the current docs it might be best to just merge it and then implement any remarks which I may have when I finally get around to looking at this as follow-up patches on top.

**Comment by jwrdegoede** [comment]
Hmm, I had in my mind that this was a pretty extensive change to the README, so that I would need a signicant chunk of time to review it. But I now see that it is just 2 small additions and those look fine to me.

So let me merge this right away.

**Comment by onitake** [comment]
@jwrdegoede Thanks!

**Pull request merged**
