### PR TITLE
please add chuwi vx8 3g 32gb firmware 

### PR DESCRIPTION
**Pull request by pepelillo**

### CODE REVIEW

**Comment by onitake** [comment]
Thank you!

Can you also add converted firmware, do some testing and find out the correct device parameters?
The Windows driver firmware alone is not very useful for Linux users.

**Comment by pepelillo** [comment]
That's the point!!

Don't know how to do it!! I've seen your "tutorial" but I'm not used to
deal with files in hex, and for me directions to do it is not so clear
(my fault for sure) so I can't help. Maybe if you can give me more
"begginer" directions I'll try to do it.

I've search for .fw file in windows or .h but no luck.

Sorry.

I have also a Chuwi v89, same situation.

Thanks for your help, anyway.

**Comment by onitake** [comment]
I'm sorry, I never intended this to be a beginner's tutorial.

The Silead controllers are exceptionally hard to use correctly, and I was hoping for a concentrated community effort. Others have had some success, and I tried to give as much support as I could. I also hoped that they would document what they did and maybe write some articles for beginners. But as I said, these Silead controllers are very hard to use correctly.

As of last year, there is some work going on in the Linux kernel input subsystem community, and it seems that there will be a solution to the nastiest parts of the firmware problem soon.
It will still require help from users and a collection of firmware for all the various devices.

As for extracting data from a hex dump, maybe this will help you?
https://www.youtube.com/watch?v=e9XookU7v1k
Or try the ghex documentation: https://developer.gnome.org/ghex/3.6/ghex-usage.html.en

**Comment by pepelillo** [comment]
Ok, I understand, I'll give a try with GHEX, hope I understand the directions you give in the doc. Thanks If I extract the firmware I'll add it to the Pull req.
Thanks

**Comment by onitake** [comment]
Thank you very much, I look forward to it!

**Comment by pepelillo** [comment]
I've been searching for strings in the binary driver but your "serial"
described in the tutorial does not exactly the same in my case (not
specifically sequential), but I've downloaded some of the firmware
tested to open in GHEX and some of them seems to suffer the same case.

May I cut the file the same way as these cases? (a bit different as
described in the tutorial)

Thanks for your help

**Comment by pepelillo** [comment]
Hello again.

I've been using Ghex as you advised to extract standar fw from windows
binary driver. I've take hi8 driver (already extracted) as a template.
Ive extracted a firmware.fw file using the same criteria. But at
converting to ACPI firmawre using fwtool I've found this:

fwtool -c firmware.fw -m 1680 -w 1280 -h 800 -t 5 silead_ts.fw

throws:

Loading firmware.fw...
Got page 0xb2
Got page 0x00
Got page 0x01
Got page 0x02
Got page 0x03
Got page 0x20
Got page 0x21
Got page 0x22
Got page 0x23
Got page 0x24
Got page 0x25
Got page 0x26
Got page 0x27
Got page 0x28
Got page 0x29
Got page 0x2a
Got page 0x2b
Got page 0x2c
Got page 0x2d
Got page 0x2e
Got page 0x2f
Got page 0x30
Got page 0x31
Got page 0x32
Got page 0x33
Got page 0x34
Got page 0x35
Got page 0x36
Got page 0x37
Can't parse firmware: Invalid firmware: invalid address 7981350 at page
0x37, max 128 at ./fwtool line 121.

any clue?

thanks

**Comment by onitake** [comment]
Good work!
Looks like you just included a bit too much data.
Check the end of the file cut off anything that doesn't fit into the data format described in the readme.
Or, post the extracted silead_ts.fw somewhere and I'll take a look.

**Comment by pepelillo** [comment]
Hello again.

I've step forward a bit.
I've found what seems to be 2 firmware sections in binary driver. I've
split both in two separate firmware files. Now they can be converted
using fwtool, :-)

But unforfortunately your driver does not load.

I'm unsing a ubuntu distro in my tablet (linuxium distro) with 4.10
kernel, compiled your driver ok, copied the silead_ts.fw to
/lib/firmware/silead/, unload silead mainstream driver and loaded yours:

then I got:

gsl_ts_probe: got a device named MSSL1680:00 at addrress 0x40, irq 191,
flags 0x0
Direct firmware load for silead_ts.fw failed with error -2
gsl_ts_probe: failed to load firmware: -2

in both cases:

Can you give me a clue?

Need desperately to have a working touchscreen with android-x86 in my
tablet. I know youling256 deal with his Onda tablet.....;-(

Thanks for your help

**Comment by pepelillo** [comment]
By the way, I also tested the standard firmware files with mainstream
silead.ko driver but does not work in both cases (no demesg output)





--------------------------------------------------


Hello again.

I've step forward a bit.
I've found what seems to be 2 firmware sections in binary driver. I've
split both in two separate firmware files. Now they can be converted
using fwtool, :-)

But unforfortunately your driver does not load.

I'm unsing a ubuntu distro in my tablet (linuxium distro) with 4.10
kernel, compiled your driver ok, copied the silead_ts.fw to
/lib/firmware/silead/, unload silead mainstream driver and loaded yours:

then I got:

gsl_ts_probe: got a device named MSSL1680:00 at addrress 0x40, irq 191,
flags 0x0
Direct firmware load for silead_ts.fw failed with error -2
gsl_ts_probe: failed to load firmware: -2

in both cases:

Can you give me a clue?

Need desperately to have a working touchscreen with android-x86 in my
tablet. I know youling256 deal with his Onda tablet.....;-(

Thanks for your help

**Comment by onitake** [comment]
Yes, recent kernels have trouble controlling the power pin of the chip due to changes in the ACPI subsystem. This causes initialisation to fail, no matter which driver you use.

The linux-input people are working on this, and it seems a solution will be published soon, along with a new updated silead driver. Discussion is here: https://patchwork.kernel.org/patch/9531463/

In the meantime, I recommend going back to an older kernel and using gslx680-acpi. I believe 4.0.5 was working fine, but you'll have to test yourself.

Once silead.ko gets proper ACPI platform support, you should switch to that driver. I'm planning to update the README with a howto soon.

**Comment by pepelillo** [comment]
Thanks for the info.

How can I test the 2 firmware files that I split?, In my case is
difficult to get a linux distro with kernel 4.05,

Youling reported that your driver works with 4.8.17......

You are making a great work.

B.R

**Comment by onitake** [comment]
You can always downgrade after installation.
Most distributions keep an archive of old package version, just get the package from there and install it, then select it during boot.
Ubuntu, for example: http://kernel.ubuntu.com/~kernel-ppa/mainline/

Or just build your own kernel using the running configuration (`/boot/config-$(uname -r)` or `/proc/config.gz`): cd linux-4.0.5; cp /boot/config-$(uname -r) ./.config; make oldconfig; make

**Comment by onitake** [comment]
The power pin problem should be solved in the meantime.
Can you retest using a current kernel?

Note that Linux ships with an "official" Silead driver now.
If you still want to try with gslx680-acpi, make sure to disable silead.ko. It uses firmware in "vanilla" format and needs a DMI quirk for each device.

If you would like to try silead.ko instead, please refer to this PR: #56 
It should give you a general idea of what you need to do to get it working.

**Comment by onitake** [comment]
Ok, I'll merge this now and add the missing readme entry.
If you would like to discuss further, please open an issue.

**Pull request merged**
