### PR TITLE
Add Vinga Twizzle J116 notebook.

### PR DESCRIPTION
**Pull request by and3rson**

### CODE REVIEW

**Comment by and3rson** [comment]
Guys, you are freaking awesome.

**Comment by onitake** [comment]
Thanks!
Are you also going to add mainline Linux kernel driver support and a matching firmware file in `firmware/linux/silead` ?

**Comment by and3rson** [comment]
Sure, I'm in process of adding it. Never contributed to kernel before so I'm getting a grip on it. I'll comment here once I submit a patch.

**Comment by onitake** [comment]
That's great, thank you!
Do you need to add anything else or can I merge it?

**Comment by and3rson** [comment]
I think we're good here. My kernel patch has been approved. I've also copied the silead_ts firmware into firmware/linux/silead in this PR and named it to match the firmware string in my kernel patch.

**Comment by onitake** [comment]
All right, merged.

**Comment by and3rson** [comment]
Thanks @onitake! One last question: any ideas why doesn't the multitouch feature work with the ACPI driver? Works only with kernel's silead. Or is it a known issue?

**Comment by onitake** [comment]
I don't know for sure, I haven't touched that code in a long time.
The driver should support multi-touch, but I believe it's because of the way finger association is handled in gslx680-acpi. This is not an issue in silead.c, or it was fixed at some point.

**Pull request merged**
