### PR TITLE
Added Trekstor Primetab T13B

### PR DESCRIPTION
**Pull request by mcepok**
I tested the firmware using Xubuntu 18.04 adding the changes you described to drivers/platform/x86/silead_dmi.c and it works like expected. However, without a custom kernel, the touchscreen behaves oddly.

The changes I made were for the Ubuntu 4.15 kernel. It seems like the silead_dmi.c is now called touchscreen_dmi.c . Is there anything else I have to consider before submitting a patch to mailing list?

### CODE REVIEW

**Comment by onitake** [comment]
Yes, there is one thing: please move gsl1680-trekstor-primetab-t13b.fw to [firmware/linux/silead](https://github.com/onitake/gsl-firmware/tree/master/firmware/linux/silead) and add an entry to [firmware/linux/README.md](https://github.com/onitake/gsl-firmware/tree/master/firmware/linux/README.md). This will make installation more convenient for other Primetab users.

Aside from that I think you're all set!
Thank you very much!

**Comment by mcepok** [comment]
Ah, yes, that makes sense. I already wondered why you want to have the same file twice in the same folder.

Now it should be right.

**Comment by onitake** [comment]
Perfect, thanks!

**Comment by mcepok** [comment]
Hi again,
since my patch is soon part of the mainline kernel ( https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=30394a8e8c5601eb6936402c0f94f619d002fa97 , so 4.20-rc1 for now), can you merge the pull request into the repo?

**Comment by onitake** [comment]
Sorry, I was a bit busy lately. Merging this now.

**Pull request merged**
