### PR TITLE
Adding support for new device "iLife ZedBook II"

### PR DESCRIPTION
**Pull request by MJaoune**
I have extracted the firmware file using "scanwindrv" from SileadTouch.sys and then used fwtool to convert it to a "gslx680_ts_acpi" compatible firmware.

Panel resolution was obtained using trial and error until I could get precise touch points using finger and the device's shipped pen.

### CODE REVIEW

**Comment by onitake** [comment]
Thanks a lot!
Can you rename the folder to `firmware/ilife/zedbook2` and change the readme accordingly?
I prefer not having any uppercase letters or special characters in there. It should only serve as a mnemonic.

**Comment by onitake** [comment]
Dashes ( `-` ) are ok though.

And yes, there are some firmware entries with uppercase characters in the repo already, but I'd prefer having at least the manufacturer name in lowercase.

**Comment by MJaoune** [comment]
Done.

**Comment by onitake** [comment]
Awesome, thanks!

**Pull request merged**
