### PR TITLE
Add CSL Panther Tab HD

### PR DESCRIPTION
**Pull request by mvzlb**

### CODE REVIEW

**Comment by onitake** [comment]
Thanks for the contribution!

Since you added a file in firmware/linux/, can you please give a link/reference to where you're introducing the necessary kernel support? Without this, the file isn't very useful.

Cc @jwrdegoede

**Comment by mvzlb** [comment]
> Since you added a file in firmware/linux/, can you please give a link/reference to where you're introducing the necessary kernel support? Without this, the file isn't very useful.

It's on the way via https://lkml.org/lkml/2022/12/20/372

**Comment by onitake** [comment]
Awesome, thank you very much!

**Comment by jwrdegoede** [comment]
> It's on the way via https://lkml.org/lkml/2022/12/20/372

Thanks, replying here since I'm not reading email during the Christmas break. Question about the kernel patch looking at the images at: https://www.csl-computer.com/csl-panther-tab-hd-usb-3-1-128gb-windows-11-home.html  I see a Windows icon on the tablet.

Typically this is a capacitive touch buttons sending windows key (KEY_LEFTMETA) events.

What happens if you add:

```
        PROPERTY_ENTRY_BOOL("silead,home-button"),
```

To the list of properties, run evtest or evemu-record on the touchscreen and then touch the Windows logo ?  If the Windows logo then sends KEY_LEFTMETA events, please submit a new version of the patch with that added.

Either way please also add a comment here with the result of the tests.

**Comment by mvzlb** [comment]
> Typically this is a capacitive touch buttons sending windows key (KEY_LEFTMETA) events.

Apparently not in this tablet. If I add this property, the `KEY_LEFTMETA` is listed as supported event, but nothing happens when I touch the logo:

```
Input driver version is 1.0.1
Input device ID: bus 0x18 vendor 0x0 product 0x0 version 0x0
Input device name: "silead_ts"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 125 (KEY_LEFTMETA)
    Event code 330 (BTN_TOUCH)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      5
      Min        0
      Max     1505
    Event code 1 (ABS_Y)
      Value   1304
      Min        1
      Max     1979
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        9
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     1505
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        1
      Max     1979
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
```

**Comment by jwrdegoede** [comment]
Ok, thanks for testing the logo-button thingie. I'll go merge your kernel-patch as is then.

**Pull request merged**
