### PR TITLE
Add Voyo VBook A1 laptop firmware

### PR DESCRIPTION
**Pull request by AstroProfundis**
I tried to convert from the vendor provided driver, and it just works on my device.

My kernel is 4.13.1-pf, running ArchLinux, after calibrating with https://github.com/reinderien/xcal it looks fine for me now. No futher test made.

The vendor driver is provided with the machine itself on disk, and can be downloaded from Baidu Cloud Storage, I can't find a working download link on Voyo's English website. All driver files are included in the directory, although I only have the `.h` used.

### CODE REVIEW

**Comment by AstroProfundis** [comment]
Oops, didn't noticed issue #37 , it would be good if someone can test all these different(?) versions, I may not have enough time to do so.

**Comment by onitake** [comment]
Great, thank you very much!

**Comment by biuDabiu** [comment]
您好!我是一个中国网友，英文不太精通，我有问题需要向你咨询或者说是求帮助，希望能帮助我。我有一个voyo v3pro电脑，装了安卓x86的凤凰os，经过解决后能够启动了，可是触控面板不能用，能不能帮忙解决。在此感谢。

**Comment by onitake** [comment]
@biuDabiu Please don't post in Chinese here. Google Translate does quite a good job, so please use at least that:

> Hello! I am a Chinese netizen, English is not proficient, I have questions need to consult or ask for help, hoping to help me. I have a voyo v3pro computer, installed Andrews x86 phoenix os, after the solution can be activated, but the touch panel can not be used, can help solve. Thanks here.

Please look at #37 - this thread here is a pull request for the A1, not a support forum for the V3.

**Comment by biuDabiu** [comment]
@onitake All right. Next time using the Google translate to post.

**Comment by onitake** [comment]
Thank you!

**Pull request merged**
