### PR TITLE
optimized firmware for ST70416-6

### PR DESCRIPTION
**Pull request by holzingerm**
generating command from original Windows 10 firmware
./fwtool -c SileadTouch.fw -3 -m 1680 -w 885 -h 635 -t 10 -f track
silead_ts_ST70416-6.fw

### CODE REVIEW

**Comment by onitake** [comment]
Thank you. Two criticisms:
- Please add a patch that updates https://github.com/onitake/gsl-firmware/tree/master/firmware/trekstor/surftab7new/README.md (see https://github.com/onitake/gsl-firmware/blob/master/firmware/trekstor/surftab7old/README.md for a complete example) and https://github.com/onitake/gsl-firmware/blob/master/README.md
- Please rename to silead_ts.fw to keep the file names consistent. The old silead_ts.fw should be overwritten.

**Comment by holzingerm** [comment]
hope its more like you want the patch
I do not know the exact Touch panel resolution so I wrote the valuse I used to gereate to firmware

**Comment by onitake** [comment]
It's perfect. :)

**Comment by onitake** [comment]
Is the firmware working well with these parameters?
In that case, I'm going to add a Tested: Yes to the device list.

**Comment by holzingerm** [comment]
Yes I work with that firmware on a daily basis. its near to perfect on the right and bottom edge.
only top and left (which can't be influenced by -w & -h parameters) have i small gap between the edge and max finger position

I use it on android-x86 were I try to try to get the tablet running, and also on ubuntu 15.10 to test kernel modules,... before porting to android

**Comment by holzingerm** [comment]
maybe I find some time to see if Ican also introduce an offset correction value to the complete touchscreen area.
If i imagine correctly the small offset would be the last 5points that are missing to get a beatifull value for the fwtool. :) such like

```
./fwtool -c SileadTouch.fw -3 -m 1680 -w **890** -h **640** -t 10 -f track **-ox -5 -oy -5**
silead_ts_ST70416-6.fw
```

but first I need to find out why my init.sh scrip can not load the module with the parameter on startup
only if I manually execute the script or if I manually modprobe it

**Comment by onitake** [comment]
Hmm. Actually, this should be taken care of by the calibration.
But I talked to another user that had offset problems, and I think I'm going to add xmin and ymin values, so the left side of the touch screen can be calibrated. It may also help with xflip and yflip.

**Pull request merged**
