### PR TITLE
Adding Digma e200 touchscreen firmware

### PR DESCRIPTION
**Pull request by sinxwal**
Hi! I need some help with this firmware. I have extracted it from SileadTouch.sys file. 
It is tested on "Digma Citi E200 (ES2000EW)" tablet, you can merge it, It works nice with gslx680-acpi driver.
However, when I use native linux silead module (4.13.0-12-generic, modprobe silead), it has very small resolution on the screen and it is also fliped in y direction. Is there any workaround?

Also, can you tell me what is the best(less custom) silead module to use nowadays?

### CODE REVIEW

**Comment by jwrdegoede** [comment]
Hi,

On 13-10-17 21:52, Sergey Tshovrebov wrote:
> Hi! I need some help with this firmware. I have extracted it from SileadTouch.sys file.
> It is tested on "Digma Citi E200 (ES2000EW)" tablet, you can merge it, It works nice with gslx680-acpi driver.
> However, when I use native linux silead module (4.13.0-12-generic, modprobe silead), it has very small resolution on the screen and it is also fliped in y direction. Is there any workaround?
 >
 > Also, can you tell me what is the best(less custom) silead module to use nowadays?

The best driver to use now a days is the in kernel driver,
as that will be present in distro provided kernels by default
so then users only have to install the firmware, and not
also built the driver themselves.

For each new tablet the info which gets added to the
custom firmware header from the gslx680-acpi needs to be added
directly to the kernel, like this:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/platform/x86/silead_dmi.c?id=c3a73ed8a82b666ac01466d3badd7824eae89c44

Regards,

Hans

**Comment by onitake** [comment]
@jwrdegoede That's not enough, a <device>_props stanza is also needed here. Like this: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/platform/x86/silead_dmi.c?id=4edfc5406ac9d3b59f770dd7436fdcfd5d593216

@sinxwal Please patch your silead_dmi.c as suggested, then rebuild the silead.ko module and test it against your device. Please make sure that you also use a unique firmware name.

Once it's working, please post your silead_dmi.c modifications here and Hans will merge them. I will then commit your silead_ts.fw to the appropriate place: https://github.com/onitake/gsl-firmware/tree/master/firmware/linux/silead

**Comment by onitake** [comment]
Oh, and thank you for the firmware!

**Comment by sinxwal** [comment]
Thank you guys. So touch is not working properly because it is missing in the kernel module itself?

**Comment by sinxwal** [comment]
I've updated https://github.com/sinxwal/linux/blob/master/drivers/platform/x86/silead_dmi.c
Still needs some testing, I'll report when i'm done with it.

**Comment by RussianNeuroMancer** [comment]
@jwrdegoede @onitake 
Please take a look at strings inside firmware.fw in this pull request. Is it expected that there is some (I assume) garbage data after extraction from SileadTouch.sys, or it's Ok?

**Comment by jwrdegoede** [comment]
Hi,

On 14-10-17 11:32, RussianNeuroMancer wrote:
> @jwrdegoede <https://github.com/jwrdegoede> @onitake <https://github.com/onitake>
> Please take a look at strings inside firmware.fw in this pull request. Is it expected that there is some (I assume) garbage data after extraction from SileadTouch.sys, or it's Ok?

firmware.fw looks good to me, I do not see any garbage data at the end
(looking in a hex viewer). Just the expected raw firmware patterns.

Regards,

Hans

**Comment by RussianNeuroMancer** [comment]
@jwrdegoede  yep, I probably used wrong script to extract firmware from SileadTouch.sys and assume @sinxwal used the same (before he open this pull request we talk about his tablet on 4pda). I also see that  firmware.fw is already unscrambled.

**Comment by sinxwal** [comment]
Yes, after extracting it was already unscrambled.
There is no need to unscrabe after cuting from SileadTouch.sys

**Comment by sinxwal** [comment]
@onitake What is the purpose of adding new tablet config into silead_dmi.c:silead_ts_dmi_table?
It has no effect, as silead.ko module does not use it anyway.
Evidently, after rebuilding the silead.ko module with this updates nothing has changed with my tablet touchpad. It is flipped-y and has less resolution than screen does.

**Comment by onitake** [comment]
@sinxwal If the DMI match is correct, it should have an effect.

@jwrdegoede What's the best way to test if the driver is loading the correct firmware and settings?

When I wrote gslx680_acpi, I put all the device configuration directly into the firmware images. With `silead.ko`, this no longer works because it uses "vanilla" firmware from the Windows/Android drivers. Instead, a DMI configuration needs to be added to the kernel driver for each device. It's not an optimal solution, but provides the most convenience for users - once a device has been added.

**Comment by RussianNeuroMancer** [comment]
@onitake maybe it's make sense tp integrated this patch?
https://bugzilla.kernel.org/show_bug.cgi?id=187531#c1

**Comment by jwrdegoede** [comment]
Hi,

On 16-10-17 08:52, Gregor Riepl wrote:
> @sinxwal <https://github.com/sinxwal> If the DMI match is correct, it should have an effect.
> 
> @jwrdegoede <https://github.com/jwrdegoede> What's the best way to test if the driver is loading the correct firmware and settings?

What I always do is have the firmware file from the dmi data
be the only file under /lib/firmware/silead, that way if the
driver complains that it cannot find silead/mssl1680.fw you
know that the dmi data is no being picked up.

Regards,

Hans

**Comment by sinxwal** [comment]
@jwrdegoede @onitake I take pleasure of introducing working patch for silead_dmi.c file to support Digma E200 tablet. Recently my mistake was in the match section, you were right. Finally I have built kernel with this patch and successfully got silead module requesting my firmware file. Next boot file was successfully read and touch started responding.

[add_digma_e200_props.patch.zip](https://github.com/onitake/gsl-firmware/files/1388887/add_digma_e200_props.patch.zip)

We need this in upstream now.

Also, this PR is ready for merge too.

**Comment by onitake** [comment]
Great work, @sinxwal !
Merged #47 .

**Comment by jwrdegoede** [comment]
Hi,

On 16-10-17 22:01, Sergey Tshovrebov wrote:
> @jwrdegoede <https://github.com/jwrdegoede> @onitake <https://github.com/onitake> I take pleasure of introducing working patch for silead_dmi.c file to support Digma E200 tablet. Recently my mistake was in the match section, you were right. Finally I have built kernel with this patch and successfully got silead module requesting my firmware file. Next boot file was successfully read and touch started responding.
> 
> add_digma_e200_props.patch.zip <https://github.com/onitake/gsl-firmware/files/1388887/add_digma_e200_props.patch.zip>
> 
> We need this in upstream now.

Ok, I can take care of submitting this upstream, but I need to
know which email address to use when I set you as the author
of the patch in git and I need a Signed-off-by from you
(which means that you are ok with this patch going
upstream under the GPL).

Can you send me a mail at: hdegoede@redhat.com

Subject: Adding Digma e200 touchscreen firmware
And in the body of the mail:

Signed-off-by: Sergey Tshovrebov <youremail@domain.cc>

Then I will take care of getting this upstream.

Thanks & Regards,

Hans

**Comment by sinxwal** [comment]
@jwrdegoede, done.
Thanks!

**Pull request merged**
