### PR TITLE
Changed controller type to 3680 and optimize resolution

### PR DESCRIPTION
**Pull request by Split7fire**
After disassembling the unit, it's figured out that there GSL3680 chip inside. So, I changed type and see no difference (WTF?). These chips 1680 and 3680 so similar?
Also I changed resolution to better fit to screen. There is no dead zone on the right of the screen now, but I cant figured out how to use left dead zone (20 - 40 pixels). Height resolution seems just fine. Any ideas?

### CODE REVIEW

**Comment by onitake** [comment]
No WTF. The device type does not actually change anything, as all the Silead chips use the same protocol, but they all require device-specific firmware (*this* is the WTF).

If it doesn't work correctly, you need to dig further for a firmware blob that fits your specific device. One possibility is to extract it from the Windows or Android drivers that came with it.

**Comment by Split7fire** [comment]
This firmware is actually stripped off the _official_ driver for Windows 10. It seems that whether resolution I choose, I always get dead zone on the left of touchpad. As for now I can't remember is this typical for Windows 10 or not.

**Comment by onitake** [comment]
As far as I know, Windows does not enforce a dead zone (unless there are some softkeys there or something), so I don't see why it wouldn't report touches.

You could try enabling debug messages in the driver and see what the chip reports.

**Comment by Split7fire** [comment]
How can I enable debug in gslx680-acpi?

**Comment by onitake** [comment]
Sorry for the late response.
I thought I had already replied to you, but it looks like the message never came through. You can enable debugging messages by replacing `dev_vdbg` with `dev_warn` in line  369: https://github.com/onitake/gslx680-acpi/blob/master/gslx680_ts_acpi.c#L369

**Comment by Split7fire** [comment]
Ok, I managed to do that. What I get:
when I press near edges, I get not max numbers on x & y - I conclude I need to change resolution
also normally p = 0 (in function it reads for pressure, what it is?) while at edges it changes to p = 4.
Any ideas?

**Comment by Split7fire** [comment]
After some measurement, I got this numbers (assuming firmware generated with 1920x1200):
"x": 3(min) - 1277(max)
"y": 20(min) - 1890(max)

**Comment by onitake** [comment]
Nice!
With these results, I'd go with 1300 for x_max and 1900 for y_max, but it's up to you.

About the p value: It's not clear what it means exactly, as the manufacturer has never released a proper hardware specification or data sheet. A recent comment on linux-input suggests it's some kind of flag value, indicating when a finger leaves the screen or when a soft-key (such as the Windows logo on some tablets) has been pressed.

I originally assumed it would report touch pressure, but the Silead controllers don't have such a feature.

**Comment by Split7fire** [comment]
I'll test this more thoroughly.

> it's some kind of flag value, indicating when a finger leaves the screen

I was thinking of a same thing.
Also out-of-topic: any thoughts about realisation of soft "windows" key?

**Comment by onitake** [comment]
> I was thinking of a same thing.
> Also out-of-topic: any thoughts about realisation of soft "windows" key?

Please have a look at this patch: http://www.spinics.net/lists/linux-input/msg51877.html
Shouldn't take too long until it makes it into the kernel.

**Comment by Split7fire** [comment]
Ok, so one more out-of-topic question: if I write patch to silead.c, containing my spec and firmware, where should I send it for upstream merging?

**Comment by jwrdegoede** [comment]
On 19-06-17 03:19, Vladislav Vishnyakov wrote:
> Ok, so one more out-of-topic question: if I write patch to silead.c, containing my spec and firmware, where should I send it for upstream merging?

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst

**Comment by onitake** [comment]
The correct destination would be linux-input. Please also send a Cc to Hans de Goede. He's the main author and maintainer of the driver.

But before you do, make sure you follow the guidelines for contributing to the Linux kernel.
Examples of relevant documents:
- https://www.kernel.org/doc/html/v4.11/process/submitting-patches.html
- https://www.kernel.org/doc/html/v4.11/process/coding-style.html

**Comment by onitake** [comment]
Do you still need work on this firmware or can I merge it?

**Comment by Split7fire** [comment]
@onitake I made some improvements over firmware. Will try to attach more recent firmware as soon as possible.

**Comment by onitake** [comment]
Thanks, looking forward to it.

**Comment by Split7fire** [comment]
@onitake It is ready to merge.

**Comment by onitake** [comment]
Done, thanks!

**Pull request merged**
