### PR TITLE
Add RWC NANOTE P8 UMPC Convertible firmware in format expected by the mainline kernel

### PR DESCRIPTION
**Pull request by yuk7**

### CODE REVIEW

**Comment by onitake** [comment]
Hi @yuk7 , thanks for your contribution.

Can you post a link to the Linux kernel patch (i.e. on https://patchwork.kernel.org/ ) where support for this device was introduced? I didn't see anything on the linux-input mailing list.

**Comment by yuk7** [comment]
Thank you for replying.

https://patchwork.kernel.org/project/platform-driver-x86/patch/20220104081920.1794275-1-yukx00@gmail.com

https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.10/platform-x86-touchscreen_dmi-add-info-for-the-rwc-na.patch

This. 
It has already been merged into a 5.10 stable queue branch.

**Comment by yuk7** [comment]
@onitake 
Thank you for replying.
The device is  nanote p8.(firmware/rwc/nanote-p8)

Commit is:
https://patchwork.kernel.org/project/platform-driver-x86/patch/20220104081920.1794275-1-yukx00@gmail.com

https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.10/platform-x86-touchscreen_dmi-add-info-for-the-rwc-na.patch

It has already been merged into a 5.10 stable queue branch.

**Comment by onitake** [comment]
Sounds good, thank you!

**Pull request merged**
