### PR TITLE
Bush ac101bcs

### PR DESCRIPTION
**Pull request by stpf99**
Hi this for "BUSH Bush Windows tablet", if is too much commits i can re upload to new fork, 
Linux PR: https://github.com/akiyks/linux/pull/3
Systemd PR: https://github.com/systemd/systemd/pull/29268

### CODE REVIEW

**Comment by onitake** [comment]
Please follow this guide for submitting Linux kernel patches: https://www.kernel.org/doc/html/latest/process/submitting-patches.html
It's a bit more involved than simply opening a PR on GitHub, due to the extensive review process involved.

The appropriate recipients are the [linux-input](http://vger.kernel.org/vger-lists.html#linux-input) and [platform-driver-x86](http://vger.kernel.org/vger-lists.html#platform-driver-x86) mailing lists.

**Comment by stpf99** [comment]
in manual for only one file changes is described as it i made:
 copy source file to *.orig ,
 next edited in nano original file by pasting changes from  tested sources for proper places and made patch by this cmds : 
SRCTREE=linux
MYFILE=drivers/platform/x86/touchscreen_dmi.c
iff -up $SRCTREE/$MYFILE{.orig,} > /home/tomek/patch

resulted patch file i copied to email in mozilla thunderbird befor i'm described for which device it is and mentioned your firmware repository for PR and systemd PR changes for rotation

**Comment by stpf99** [comment]
Hi i have prepared patch , but don't know how to send it in way 100% correctly, i would ask for help to send it in my opinion if someone have time 

0001-platform-x86-touchscreen_dmi-Add-info-for-the-BUSH-B.patch 
https://gist.github.com/stpf99/041122e9d1b844671887a4f1650164f8

**Comment by onitake** [comment]
Thanks, me or @jwrdegoede can submit it on your behalf if you like, butit would be better if you submit it yourself.
That way, you can directly answer comments.

Anyway, no matter if you submit it yourself or not, please add a sign-off to certify the patch comes from you and that you agree it can be included in the Linux kernel: https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

Here's an example of what the mail should look like: https://lore.kernel.org/all/20190203183423.7661-1-k.renzig@gmail.com/

When you're submitting it yourself, just add the commit message and your `Signed-off-by:` to the body of the mail.
As recipients, you can use the following:
```
To: linux-input@vger.kernel.org, platform-driver-x86@vger.kernel.org, linux-kernel@vger.kernel.org
Cc: Hans de Goede <hdegoede@redhat.com>, Gregor Riepl <onitake@gmail.com>
```

**Comment by stpf99** [comment]
Ok @onitake , Patch now including my Sign-off and is ready to send , I agree this statement by this . will be much faster if you or @jwrdegoede send and accept this patch.

**Comment by jwrdegoede** [comment]
@stpf99 thank you for all your work on this.

I have received your kernel patch for this by email. I'll take care of merging this and sending it to Linus for inclusion into 6.6-rc# .

Note I'm travelling this week, so I won't get around to actually merging this
until next week.

**Comment by jwrdegoede** [comment]
i see that you have 68 commits here now. It would be good if you could start over and do 1 or 2 commits just adding the new fw diretly in the right format(s) including in the format expected by the mainline kernels.

Either do a forced push to this branch with just 1-2 commits or start a new clean pull-req for that.

**Comment by onitake** [comment]
On 24 September 2023 23:00:31 CEST, Hans de Goede ***@***.***> wrote:
>i see that you have 68 commits here now. It would be good if you could start over and do 1 or 2 commits just adding the new fw diretly in the right format(s) including in the format expected by the mainline kernels.
>
>Either do a forced push to this branch with just 1-2 commits or start a new clean pull-req for that.
>

I had actually intended to squash the whole PR once it's complete, but it would also be ok if you did that instead. ;)

**Comment by stpf99** [comment]
how 68 commits can be squashed to that big one by gui on web ?

**Comment by onitake** [comment]
On 25 September 2023 11:53:43 CEST, "Tomasz Świątek" ***@***.***> wrote:
>how 68 commits can be squashed to that big one by gui on web ?
>

It can only be squashed when merging, unfortunately.
Otherwise you'll have to do it from the command line.

**Comment by onitake** [comment]
@stpf99 @jwrdegoede I didn't see a patch on https://patchwork.kernel.org/project/linux-input yet, have you submitted anything?

@stpf99 Is it ok if I merge this PR, or do you still need to change anything?

**Comment by jwrdegoede** [comment]
> @stpf99 @jwrdegoede I didn't see a patch on https://patchwork.kernel.org/project/linux-input yet, have you submitted anything?

Yes @stpf99 did submit a kernel patch but only to me directly not to the list. I was a bit slow to process it (sorry). I have pushed this to pdx86/fixes now: https://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86.git/log/?h=fixes  and I plan to send a pull-request to Torvalds for pdx86/fixes coming Friday. So this should go upstream soon.

So from the kernel patch side of things there is nothing blocking merging this.

**Comment by stpf99** [comment]
> @stpf99 Is it ok if I merge this PR, or do you still need to change anything?

No needs to be changed , fw filename is correct and have corresponding name in patch and this repository and in this form things works as expected.

**Comment by onitake** [comment]
All right, I squashed and merged the PR!

Thank you very much for your contribution.

**Comment by stpf99** [comment]
thank you,  today tablet work's on installed 6.6.0-rc5 kernel downloaded from ubuntu kernel ppa, and all related touchscreen functions works and slider for brightness in gnome also, PR for proper rotation is in systemd merged also...

**Pull request merged**
