### PR TITLE
Bush Bush Windows tablet

### PR DESCRIPTION
**Pull request by stpf99**
Hi this for "Bush Bush Windows tablet", not tested with proper quirks in kernel, but device is clone "archos 101b cesium" , firmware SileadTouch.sys is diffrent on  Windows 10 , but i manually copied this file from working windows installation and extracted like in  howto is described, in free time i install debian and prepare kernel with quirks to confirm if all is ok

### CODE REVIEW

**Comment by stpf99** [comment]
i corrected id information from dmidecode for proper device recognition "BUSH" (manufacturer), "Bush Windows tablet" device name

**Comment by onitake** [comment]
Thanks for contributing!
Please add an entry to the list in the toplevel README file as well.

Are you planning to test the firmware and submit a kernel patch soon? If yes, I'll wait with merging until you're ready.

Otherwise, you can just open a new PR for moving `firmware/bush/bush_windows_tablet/gsl1680_bush_bush_windows_tablet.fw` into `firmware/linux` once you've submitted the patch.

**Comment by stpf99** [comment]
with submiting in  proper form  patch after successfull testing may be problem, i sometime ago contributed information for other device driver development but i no send patch individually i after test post here proper lines, currently i compile debian kernel with quirks for spec same as "archos 101 educ" with diffrent name and pointed to diffrent firmware file

**Comment by stpf99** [comment]
hi working with https://github.com/onitake/gslx680-acpi/  only "swap" is needed  
./fwtool -c silead.fw -m 1680 -w 1280 -h 1850 -t 10  -f swap silead_ts.fw , 
copy to lib/firmware , insmod gslx_ts_acpi.ko, working bettern on gnome on wayland with your driver, thanks

**Comment by stpf99** [comment]
do i need to recompile and install whole kernel to test changes made in touchscreen_dmi.c and if not which files need to be replaced in working kernel from compiled modules , by now i recompile with changes by "make drivers/platform/x86/" for new touchscreen_dmi.o and "make drivers/input/touchscreen/" for silead.ko, but replacing this files in working kernel modules dir's and reloading silead by modprobe -r silead a nd modprobe silead loading firmaware but not affecting any changes in behavior in comparing with original full kernel install... ?

**Comment by onitake** [comment]
Unfortunately yes, a kernel recompile is needed for changing the DMI overrides.
The problem is that touchscreen_dmi.c is not part of the silead.ko module, but of the whole ACPI subsystem in the kernel. And AFAIK, it can't be compiled as a module, so a new kernel must be compiled and loaded whenever you want to test the overrides.

**Comment by jwrdegoede** [comment]
> do i need to recompile and install whole kernel to test changes made in touchscreen_dmi.c

You need to rebuild the main kernel image typically done by `make -j8 bzImage" and then copy `arch/x86/boot/bzImage` to `/boot/vmlinuz-$version` where $version is the version (`uname -r` output) of your custom kernel.

**Comment by jwrdegoede** [comment]
> You need to rebuild the main kernel image typically done by make -j8 bzImage and then copy arch/x86/boot/bzImage to /boot/vmlinuz-$version where $version is the version (uname -r output) of your custom kernel.

Note this assumes that you already have build and are running a custom kernel and are just tweaking your patch. When testing a patch for the first time you need to do a full kernel build + install as @onitake said.

**Comment by stpf99** [comment]
I have now working touch as far i know in kernel official way and alternate way , thank you for suggestion and help, but i don't know how and don't have account to subbmit patch for official linux tree, this will be very  helpful if someone do that replacing me in this :

static const struct property_entry bush_bush_windows_tablet_props[] = {
	PROPERTY_ENTRY_U32("touchscreen-size-x", 1850),
	PROPERTY_ENTRY_U32("touchscreen-size-y", 1280),
	PROPERTY_ENTRY_BOOL("touchscreen-swapped-x-y"),
	PROPERTY_ENTRY_U32("silead,max-fingers", 10),
	PROPERTY_ENTRY_BOOL("silead,home-button"),
	PROPERTY_ENTRY_STRING("firmware-name", "gsl1680-bush_bush_windows_tablet.fw"),
	{ }
};


static const struct ts_dmi_data bush_bush_windows_tablet_data = {
	.acpi_name      = "MSSL1680:00",
	.properties     = bush_bush_windows_tablet_props,
};
	
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

{
		/* Bush Windows tablet */
		.driver_data = (void *)&bush_bush_windows_tablet_data ,
		.matches = {
			DMI_MATCH(DMI_PRODUCT_NAME, "Bush Windows tablet"),
		},
	},

**Comment by stpf99** [comment]
i can't  open pr for merge

**Pull request closed without merging**
