### PR TITLE
Append missing files for Trekstor SurfTab twin 10.1 (ST10432-8).

### PR DESCRIPTION
**Pull request by bernhardu**
Using now the firmware extracted from the header file.

Found that reading these files with ntfs-3g gave just zeros.
In Windows they have real content.

When using SDDM login manager or Plasma desktop "clicking" is not recognised.
However dragging windows is possible.
But in the same session a text mode midnight commander inside a xterm reacts as expected.
A text mode midnight commander started in a konsole does not react.
Also Synaptic, being a Gtk application, reacts as expected.

So would this be just a problem with my parameters, or is this more pointing to a problem
with Qt/Kde in Debian testing (or to my git kernel - used for a different issue of the wireless card)?

So, as you said, input is not reliable recognized with my current parameters.
Therefore switched the tested back to "no".

### CODE REVIEW

**Comment by onitake** [comment]
I recommend going a bit more low-level than that.
First, run `xinput_calibrator` to get the touch/screen mapping right.
Then test with `xinput test <dev>` or `xev`. Taps should reliably generate button down and up events. If they don't, enable finger tracking. Drag your finger across the screen and see how the values change. If it cuts off to early, try changing the width and height parameters.

**Comment by bernhardu** [comment]
I believe I found the issue why Qt5 based applications are reacting different.
After quite some debugging I got to this [commit](http://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/xcb/qxcbconnection_xi2.cpp?id=462f355e4fb16cc7a1838fa2dda0f763eee58c84):
    xcb: fix touchscreen input with certain capabilities only
    Touch screens without the "Abs MT Position X" but "Abs X" capability
    weren't detected correctly so far. This patch fixes the detection and
    enables these tochscreens.

It did not recognise my touch device as such and therefore dropped all events.
The window decoration probably works differently, therefore there it works.

As Qt5 applied this patch I assume it is valid for a touch device to just deliver "Abs X".

A package libqt5gui5_5.5.1+dfsg-17_amd64.deb with the patch applied made my inputs now recognized by the Qt5 applications.

I still need to try to tune the parameters to get X < 15 also reachable.

**Comment by onitake** [comment]
Which driver are you using exactly?
As you can see, gslx680-acpi actually registers and sends MT events:
https://github.com/onitake/gslx680-acpi/blob/master/gslx680_ts_acpi.c#L556

**Comment by bernhardu** [comment]
I am using gslx680_ts_acpi.ko, cloned from https://github.com/onitake/gslx680-acpi.git, latest commit 667efce.

Here is the output of xinput:
```
benutzer@trekstor:~/touch/4.6-10744-gc543673/gslx680-acpi$ xinput list --short
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Logitech USB-PS/2 Optical Mouse           id=8    [slave  pointer  (2)]
⎜   ↳ HID 0911:2188                             id=9    [slave  pointer  (2)]
⎜   ↳ Silead GSLx680 Touchscreen                id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ HID 046a:0011                             id=7    [slave  keyboard (3)]
    ↳ HID 0911:2188                             id=10   [slave  keyboard (3)]
    ↳ gpio-keys                                 id=12   [slave  keyboard (3)]
    ↳ HID 0911:2188                             id=13   [slave  keyboard (3)]
    ↳ Video Bus                                 id=6    [slave  keyboard (3)]
benutzer@trekstor:~/touch/4.6-10744-gc543673/gslx680-acpi$ xinput --list --long 11
Silead GSLx680 Touchscreen                      id=11   [slave  pointer  (2)]
        Reporting 6 classes:
                Class originated from: 11. Type: XIButtonClass
                Buttons supported: 7
                Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
                Button state:
                Class originated from: 11. Type: XIValuatorClass
                Detail for Valuator 0:
                  Label: Abs X
                  Range: 0.000000 - 65535.000000
                  Resolution: 0 units/m
                  Mode: absolute
                  Current value: 0.000000
                Class originated from: 11. Type: XIValuatorClass
                Detail for Valuator 1:
                  Label: Abs Y
                  Range: 0.000000 - 65535.000000
                  Resolution: 0 units/m
                  Mode: absolute
                  Current value: 0.000000
                Class originated from: 11. Type: XIValuatorClass
                Detail for Valuator 2:
                  Label: Rel Horiz Scroll
                  Range: -1.000000 - -1.000000
                  Resolution: 0 units/m
                  Mode: relative
                Class originated from: 11. Type: XIValuatorClass
                Detail for Valuator 3:
                  Label: Rel Vert Scroll
                  Range: -1.000000 - -1.000000
                  Resolution: 0 units/m
                  Mode: relative
                Class originated from: 11. Type: XITouchClass
                Touch mode: direct
                Max number of touches: 15
```
A single tap:
```
benutzer@trekstor:~/touch/4.6-10744-gc543673/gslx680-acpi$ xinput test 11
motion a[0]=42950 a[1]=17649 
button press   1 a[0]=42950 a[1]=17649 
motion a[0]=42950 a[1]=17649 
button release 1 a[0]=42950 a[1]=17649 
```
Another single tap:
```
root@trekstor:/home/benutzer/touch/4.6-10744-gc543673/gslx680-acpi# evtest 
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Silead GSLx680 Touchscreen
/dev/input/event1:      Lid Switch
/dev/input/event2:      PC Speaker
/dev/input/event3:      gpio-keys
/dev/input/event4:      HID 0911:2188
/dev/input/event5:      HID 0911:2188
/dev/input/event6:      HID 046a:0011
/dev/input/event7:      Logitech USB-PS/2 Optical Mouse
/dev/input/event8:      Video Bus
Select the device event number [0-8]: 0
Input driver version is 1.0.1
Input device ID: bus 0x18 vendor 0x0 product 0x0 version 0x0
Input device name: "Silead GSLx680 Touchscreen"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 330 (BTN_TOUCH)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   1259
      Min        0
      Max     1920
    Event code 1 (ABS_Y)
      Value    345
      Min        0
      Max     1280
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        9
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     1920
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1280
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
Event: time 1464955803.545052, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 4
Event: time 1464955803.545052, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 1212
Event: time 1464955803.545052, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 311
Event: time 1464955803.545052, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1464955803.545052, type 3 (EV_ABS), code 0 (ABS_X), value 1212
Event: time 1464955803.545052, type 3 (EV_ABS), code 1 (ABS_Y), value 311
Event: time 1464955803.545052, -------------- SYN_REPORT ------------
Event: time 1464955803.588944, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1464955803.588944, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1464955803.588944, -------------- SYN_REPORT ------------
```

Is xinput supposed to report "Abs MT Position X" for my device?

**Comment by bernhardu** [comment]
I tried to find where this "Abs MT Position X" would be set.
As far as I see 'libinput' is used for my touchscreen in the X-Server.
But I could not find any reference of the ABS_MT_POSITION_X in my libinput sources.

Should my touchscreen be managed by a different X input driver?
What do you think?
```
/var/log/Xorg.0.log
    [    36.755] (II) Using input driver 'libinput' for 'Silead GSLx680 Touchscreen'

xorg-server-1.18.3/include/xserver-properties.h
    #define AXIS_LABEL_PROP_ABS_X           "Abs X"
    #define AXIS_LABEL_PROP_ABS_MT_POSITION_X  "Abs MT Position X"

xserver-xorg-input-libinput-0.19.0/src/xf86libinput.c
    xf86libinput_init_touch(InputInfoPtr pInfo)
    {
    ...
        xf86InitValuatorAxisStruct(dev, 0,
                           XIGetKnownProperty(AXIS_LABEL_PROP_ABS_X),
                       min, max, res * 1000, 0, res * 1000, Absolute);
```

**Comment by onitake** [comment]
No, not really. MT devices should work out of the box, without any particular hacks on the userspace side. It's possible that I forgot to register something in the input subsystem, but I'm pretty sure I covered everything necessary. Other TS drivers send the same kinds of events, so I'm not sure why you're having problems.

**Comment by bernhardu** [comment]
The "evtest" shows the ABS_MT_POSITION_X events.
Therefore I would assume that the driver is working as expected.
The "xinput" test does not show the "Abs MT Position X", so I assume the libinput driver does just forward the "Abs X" events.

Does your xinput show an "Abs MT Position X" valuator?

**Comment by bernhardu** [comment]
I think I found the issue:
I wondered because calibrating did not make any difference when adding the xinput_calibrator output to the X configuration.
Then I found that libinput uses a pption "CalibrationMatrix" with 9 values.
But xinput_calibrator gave always Options MinX, MaxX, MinY, MaxY.

On my system installing the X server pulled both drivers, xserver-xorg-input-libinput and xserver-xorg-input-evdev.

Did now force X to use the evdev driver by adding this to the X configuration: Driver "evdev"
Now xinput_calibrator started to give a single Option  "Calibration" in its output.

Also xinput reports now my device with "Abs MT Position X".
Therefore Qt5 works now also as expected.
(While I think this upstream patch still would be worth to be applied to the debian Qt package...)

So could you please confirm that your configuration uses the evdev driver instead of libinput for the touchscreen?

**Comment by onitake** [comment]
Absolutely!
The libinput driver is quite new and still has many bugs and missing features. Unless you want to help with development, I recommend blacklisting it until it matures.

**Pull request merged**
