### PR TITLE
Please add firmware for the Chuwi SurBook mini

### PR DESCRIPTION
**Pull request by jlempen**
Hi all,
onitake, thanks for maintaining this repo, I've been able to extract the firmware for the Chuwi Surbook Mini.
This pull request has been hanging here for some time, I don't know why.
The firmware is working as expected with Manjaro GNOME and KDE on my Surbook Mini.
The touchscreen has a rather strange resolution of an estimated 2040x1524, the y-axis is swapped and there seems to be an offset of about 180 pixels on the x-axis, so it will only work correctly with a proper calibration matrix.
As my Manjaro distro uses libinput, the usual xinput_calibrator method won't work anymore for calibration.
Please refer to the latest comments on https://wiki.archlinux.org/index.php/Talk:Calibrating_Touchscreen to calibrate and make your calibration values permanent on your system.
Cheers,
Jürg

### CODE REVIEW

**Comment by nowaylife** [comment]
sadly i find unusable this fw...

i got working one but it works very poorly
https://ufile.io/8oxkv

as a total linux noob i tried all uploaded chuwi silead_ts.fw for gsl and extracted one by just copying it /lib/firmware but none works at all.

i might missing real basic things(noobthing)

need kindhand to solve... i mean biiig hand

**Comment by jlempen** [comment]
Hey nowaylife,
I'm sorry it doesn't work for you. For me, this firmware works perfectly, but as there is a horizontal offset on the touchscreen, you must calibrate your touchscreen and flip the y-axis in order to make it work. The firmware file is not the issue here, it is only a matter of getting the calibration matrix right.

**Comment by fenjo** [comment]
I been working with my linux system and learned thing or two, and your firmware runs good.
it was just gsl acpi firmware matter not yours
so... i support this marge REQ :)
please do onitake

**Comment by onitake** [comment]
Ok, since the firmware seems to work for several people (where did @fenjo 's comment go?), I'm going to merge it.

Thanks!

**Pull request merged**
