### PR TITLE
add files for Archos 101 Cesium Educ

### PR DESCRIPTION
**Pull request by tomlohave**

### CODE REVIEW

**Comment by onitake** [comment]
@tomlohave @jwrdegoede Is this ready for merge?
If yes, could you please rebase it to resolve the conflicts with the base branch?
Thanks!

**Comment by tomlohave** [comment]
@onitake , yes it's ready and works very well on fedora 39 beta
Willl rebase this on the afternoon
Cheers !

**Comment by tomlohave** [comment]
@onitake , it should be ready now.

**Comment by onitake** [comment]
Thank you very much for your contribution!

**Pull request merged**
